- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
      - homebrew/binary

    homebrew_cask_packages:
      - name: appcleaner
      - name: google-chrome
      - name: google-japanese-ime
      - name: slack
      - name: mysqlworkbench
      - name: jetbrains-toolbox
      - name: fork
      - name: p4v
      - name: docker
      - name: iterm2
      - name: postman
      - name: authy
      - name: clipy
      - name: wrike
      - name: kindle

    homebrew_packages:
      - name: git
      - name: zsh
      - name: zplug
      - name: docker
      - name: jq
      - name: nodebrew
      - name: anyenv

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

#    - name: homebrew tap
#      homebrew_tap:
#        name: '{{ item }}'
#        state: present
#      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: dotfiles install
      shell: bash -c "$(curl -L raw.github.com/ttakuya50/dotfiles/master/install.sh)" -s install

    - name: Install cz-conventional-changelog-ja
      npm:
        name: cz-conventional-changelog-ja
        global: yes

    - name: Install clasp
      npm:
        name: google/clasp
        global: yes
